### PR TITLE
feat: rolling average download speed

### PR DESCRIPTION
**Pull request by JustSimplyKyle**
and allow the modification of sleep_time

### CODE REVIEW

**Review by SiongSng — APPROVED** [review]
LGTM

**Comment by JustSimplyKyle** [comment]
Hold up, should be possible to do some performance improvements via VecDeque

**Comment by SiongSng** [comment]
記得加上

```rs
use std::collections::VecDeque
```

**Review by SiongSng — APPROVED** [review]
LGTM
記得 rebase

**Comment by JustSimplyKyle** [comment]
應該好了

**Pull request merged**
