### PR TITLE
feature/macro expansion

### PR DESCRIPTION
**Pull request by JustSimplyKyle**
- feat: use macro expansion way of doing stuff
- feat: use proc-macros!
- chore: remove use of clone
- feat: add target to gitignore
- feat: put bacon in struct-key-value-pair

### CODE REVIEW

**Comment by JustSimplyKyle** [comment]
api changes: Key renamed to UILayoutKey for more general usage(additionally Value renamed to UILayoutValue)

**Comment by JustSimplyKyle** [comment]
@SiongSng Help from resolving conflict, seems like the config architecture has changed

**Comment by SiongSng** [comment]
> @SiongSng Help from resolving conflict, seems like the config architecture has changed

好～我明天幫你用

**Review by SiongSng — APPROVED** [review]
:place_of_worship: 請收下我的膝蓋
LGTM

**Pull request merged**
